### ISSUE TITLE
only works with 16 bit clips

### ISSUE THREAD

**Issue by alatteri** [lcrs/ofxwrap#1]
when trying the spark from the desktop, it only accepts 16 bit clips.  says Unsupported Resolution with 8/10/12 bit clips

Flame 2016x2 Linux

**Comment by lcrs** [comment]
Yeah, I haven't done the conversion from other depths yet.  I think in Batch and on the timeline it will handle this automatically, but I should do the conversion myself anyway... since I have to get everything into 32-bit float it might as well be in one conversion step rather than Flame's auto-adapter conversion followed by my own 16-bit float RGB to 32-bit float RGBA.

**Comment by lcrs** [comment]
(fixed now. works with all bit-depths Flame supports)
